spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8080


